<?php
/******************************************************************
* Copyright © 2012 ICT Innovations.                               *
* Developed By: Falak Nawaz                                       *
*             : Nasir Iqbal                                       *
*             : Tahir Almas                                       *
* Website : http://www.ictinnovations.com/                        *
* Mail : info@ictinnovations.com                                  *
******************************************************************/

// $Id: broadcast_extension.module,v 1.0 2012/02/29 10:42:58 ictinnovations Exp $

/**
 * @file
 * Provides support to add agent extensions for call transfer in IVR.
 */

/**
 * Implementation of hook_menu().
 */
function broadcast_extension_menu() {
  $items = array();

  $items['broadcast/extension'] = array(
    'title'            => 'Extensions',
    'description'      => 'Manage Agents / Extensions',
    'page callback'    => 'broadcast_extension_list',
    'page arguments'   => array(false), 
    'access callback'  => 'broadcast_access',
    'access arguments' => array('broadcast extension'),
    'type'             => MENU_NORMAL_ITEM,
    'weight'           => 16,
  );

  $items['broadcast/extension/list'] = array(
    'title'            => 'List',
    'description'      => 'Manage Agents / Extensions',
    'page callback'    => 'broadcast_extension_list',
    'page arguments'   => array('false'),
    'access callback'  => 'broadcast_access',
    'access arguments' => array('broadcast extension'),
    'type'             => MENU_DEFAULT_LOCAL_TASK,
    'weight'           => 16,
  );
  
  $items['broadcast/extension/addnew'] = array(
    'title'            => t('Create New Extension'),
    'description'      => 'Create New Extension',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('broadcast_extension_form', array()),
    'access callback'  => 'broadcast_access',
    'access arguments' => array('broadcast extension admin'),
    'type'             => MENU_LOCAL_TASK,
    'weight'           => 17,    
  );
  
  $items['broadcast/extension/%broadcast_extension/edit'] = array(
    'title'            => t('Edit Extension'),
    'description'      => 'Edit Extension',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('broadcast_extension_form', 2),
    'access callback'  => 'broadcast_access',
    'access arguments' => array('broadcast extension admin'),
    'type'             => MENU_CALLBACK,
  );
  
  $items['broadcast/extension/%broadcast_extension/delete'] = array(
    'title'            => t('Remove Extension'),
    'description'      => 'Remove extension',
    'page callback'    => 'broadcast_extension_delete',
    'page arguments'   => array(2),
    'access callback'  => 'broadcast_access',
    'access arguments' => array('broadcast extension admin'),
    'type'             => MENU_CALLBACK,
  );
  
  return $items;
}

/**
 * Implementation of hook_permission().
 *
 * Defines access permissions that may be assigned to roles and used to restrict
 * access on extensionx module.
 */
function broadcast_extension_permission() {
  return array(
    'broadcast extension'               => array('title'=> 'broadcast extension'),
    'broadcast extension admin'         => array('title'=> 'broadcast extension admin'),
    'broadcast extension system admin'  => array('title'=> 'broadcast extension system admin'),
  );
}

/**
 * Page function for extension List
 *
 * It will show a list of available extensions in form of list
 *
 * @return
 * page html
*/
function broadcast_extension_list($admin_links = false) {
  global $user;

  $header = array(
    array('data' => t('Extension / Username'),  'field' => 'username',  'sort' => 'asc'),
    array('data' => t('Secret'),                'field' => 'passwd'),
    array('data' => t('Email'),                 'field' => 'email'),
    array('data' => t('Operations')),
  );
  
  $query = CoreDB::db_select('account', 'a')->extend('PagerDefault');
  $query->fields('a', array('account_id', 'username', 'passwd', 'email'));
//  $query->join('usr', 'u', 'a.created_by = u.usr_id');
//  $query->addField('u', 'name', 'user_name');
//  if($user->uid != 1) {
//    $query->condition('a.created_by', $user->uid,'=');
//  }
  //$query->orderBy('created', 'DESC');
  
  $result = $query->limit(50)  
            ->extend('TableSort')
            ->orderByHeader($header)
            ->execute();
    
  while ($extension = $result->fetchAssoc()) {
    $row_id = $extension['account_id'];
    $rows[$row_id][] = check_plain($extension['username']);
    $rows[$row_id][] = check_plain($extension['passwd']);
    $rows[$row_id][] = check_plain($extension['email']); 
    $rows[$row_id][] = _broadcast_extension_list_links($extension);
  }
  if (!isset($rows)) {
    $rows[] = array(array('data' => t('No extensions available'), 'colspan' => 6));
  }
  
  $output = theme('table', array('header'=>$header, 'rows'=>$rows));
  $output .= theme('pager');

  return $output;
}

/**
 * Build the Forward and Release links for a single extension.
 *
 * @see extension_list()
 */
function _broadcast_extension_list_links($extension) {
  $links['edit'] = array(
    'title' => t('Edit'),
    'href' => 'broadcast/extension/' . $extension['account_id'] . '/edit',
    'html' => TRUE,
  );
  $links['delete'] = array(
    'title' => t('Delete'),
    'href' => 'broadcast/extension/' . $extension['account_id'] . '/delete',
    'html' => TRUE,
  );
  return theme('links', array('links'=>$links, 'attributes' => array('class' => array('links', 'inline'))));
}

/**
 * Build the extension form.
 */
function broadcast_extension_form($form, &$form_state, $edit = array()) {
  global $user;
  
  // It's safe to use on both an empty array, and an incoming array with full or partial data.
  $edit += array(
    'account_id' => '',
    'username'   => '',
    'passwd'     => '',
    'email'      => '',
    'first_name' => '',
    'last_name'  => '',
    'phone'      => '',
    'address'    => '',
    'active'     => '',
    'created_by' => '',
  );

  // If we're editing an existing, we'll add a value field to the form
  // containing it's unique ID.
  if (!empty($edit['account_id'])) {
    $form['account_id'] = array(
      '#type'          => 'value',
      '#value'         => $edit['account_id'],
    );
  }

  $form['info'] = array(
    '#type'  => 'fieldset',
    '#title' => t('Extension Information'),
  );

  $form['info']['username'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Extension / Username'),
    '#required'      => TRUE,
    '#default_value' => $edit['username'],
    '#description' => t('Requires an extension file to be created in Freeswitch. Username MUST match with extension name that you created in freeswitch.'),
  );
  
  $form['info']['passwd'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Secret / Password'),
    '#default_value' => $edit['passwd'],
  );
  
  $form['info']['email'] = array(
    '#type'          => 'textfield',
    '#title'         => t('E-mail address'),
    '#default_value' => $edit['email'],
  );
  
  $form['info']['first_name'] = array(
    '#type'          => 'textfield',
    '#title'         => t('First Name'),
    '#default_value' => $edit['first_name'],
  );
  
  $form['info']['last_name'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Last Name'),
    '#default_value' => $edit['last_name'],
  );
  
  $form['info']['phone'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Phone'),
    '#default_value' => $edit['phone'],
  );
  
  $form['info']['address'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Address'),
    '#default_value' => $edit['address'],
  );
  
  $form['info']['active'] = array(
    '#type' => 'radios',
    '#title' => t('Status'),
    '#default_value' => $edit['active'],
    '#options' => array(t('Disable'), t('Active')),
  );
/*
  $form['info']['created_by'] = array(
    '#type'          => 'select',
    '#title'         => t('Assign Extension'),
    '#required'      => TRUE,
    '#options'       => array(-1=>'- Select -') + broadcast_user_option(),
    '#default_value' => $edit['created_by'],
  );
*/
  $form['buttons']['submit'] = array(
    '#type'          => 'submit',
    '#value'         => t('Submit'),
  );

  return $form;
}

/**
 * Performs validation on extension
 */
function broadcast_extension_form_validate($form, &$form_state) {
  $extension = $form_state['values'];
  if (!isset($extension['account_id'])) {
    $query = 'SELECT * FROM account WHERE username=:username';
    $result = CoreDB::db_query($query, array(':username'=>$extension['username']));
    if($rec = $result->fetchAssoc()) {
        form_set_error('username', t('Extension name is already taken. Please choose another name.'));
    }
  }

}


/**
 * Inserts a new extension, or updates an existing one.
 *
 * @param $extension
 *   A extension to be saved. If $extension['account_id'] is set, the extension will be updated.
 *   Otherwise, a new extension will be inserted into the database.
 * @return
 *   The saved extension, with its ID set.
 */
function broadcast_extension_form_submit($form, &$form_state) {
  global $user;

  include_once "/usr/ictcore/core/core.php";

  $account = $form_state['values'];
  if (!isset($account['created_by'])) {
    $extension['created_by'] = $user->uid;
  }
  $oAccount = new Account($account['account_id']);
  $oAccount->set('username',   $account['username']);
  $oAccount->set('passwd',     $account['passwd']);
  $oAccount->set('first_name', $account['first_name']);
  $oAccount->set('last_name',  $account['last_name']);
  $oAccount->set('phone',      $account['phone']);
  $oAccount->set('email',      $account['email']);
  $oAccount->set('address',    $account['address']);
  $oAccount->set('active',     $account['active']);
  $result = $oAccount->save();
  if ($result) {
    drupal_set_message(t('Extension updated successfully!'), 'status');
  } else {
    drupal_set_message(t('Unable to create Extension!'), 'error');
  }
  $form_state['redirect'] = 'broadcast/extension/list';
}


/**
 * Loader function for individual extensions.
 */
function broadcast_extension_load($account_id) {
  $sql    = "SELECT * FROM account WHERE account_id = :account_id";
  $result = CoreDB::db_query($sql, array(':account_id' => $account_id));
  if ($extension = $result->fetchAssoc()) {
    return $extension;
  } else {
    drupal_set_message(t('Error loading specified extension!'), 'error');
    return FALSE;
  }
}

/**
 * Deletes a extension, given its unique ID.
 *
 * @param $extension
 *   An array of extension containing the ID of a extension.
 */
function broadcast_extension_delete($extension) {

  include_once "/usr/ictcore/core/core.php";

  $query  = 'SELECT * FROM account';
  $result = CoreDB::db_query($query);
  $count  = $result->rowCount();
  if ($count >= 2){
    $oAccount = new Account($extension['account_id']);
    if ($oAccount->delete()){
      drupal_set_message(t('Extension deleted successfully!'), 'status');
    } else {
      drupal_set_message(t('Unable to delete Extension.'), 'error');
    }
  } else {
    drupal_set_message(t('At least one Extension must have, can\'t delete'), 'error');
  }
  drupal_goto('broadcast/extension/list');
}

/**
 * Loader function for all extensions.
 */
function broadcast_extension_option() {
  global $user;
  $sql = "SELECT account_id, username FROM {account}  
          WHERE created_by = :usr_id";
  $result = CoreDB::db_query($sql, array(':usr_id'=>$user->uid));
  $rows = array();
  while ($extension = $result->fetchAssoc()) {
    $row_id = $extension['account_id'];
    $rows[$row_id] = check_plain($extension['username']);
  }
  if (!isset($rows)) {
    return FALSE;
  }
  return $rows;
}

/**
 * Loader function for all users.
 */
function broadcast_user_option() {
  $sql    = "SELECT usr_id, username FROM usr WHERE usr_id > 0";
  $result = CoreDB::db_query($sql);
  $rows   = array();
  while ($user = $result->fetchAssoc()) {
    $row_id = $user['usr_id'];
    $rows[$row_id] = check_plain($user['username']);
  }
  if (!isset($rows)) {
    return FALSE;
  }
  return $rows;
}
