#!/usr/bin/php -q
<?php
/******************************************************************
* Copyright © 2012 ICT Innovations, All Rights Reserved           *
* License: GNU AGPL V 3.0                                         *
* Developed By: Nasir Iqbal                                       *
*             : Tahir Almas                                       *
* Modified By:  Falak Nawaz                                       *
* Website : http://www.ictinnovations.com/                        *
* Contact : support@ictinnovations.com, info@ictinnovations.com   *
******************************************************************/

/**
 * ICT Broadcast System
 * 
 * Drupal 7
 *
 * @package   Broadcast
 * @author    Nasir Iqbal <nasir@ictinnovations.com>
 * @copyright 2009 ICT Innovations Pakistan
 * @link      http://www.ictinnovations.com/ict_broadcast
 */

/* Include and initilize Drupal
*******************************/
// just to statisfy an empty veriable error
$_SERVER['REMOTE_ADDR'] = '127.0.0.1';   
$_SERVER['REQUEST_METHOD'] = 'GET';
// Change path to drupal home dir
//chdir(dirname(__FILE__).'/../../');
define('DRUPAL_ROOT', '/usr/ictdialer');
require_once DRUPAL_ROOT . '/includes/bootstrap.inc';
drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);

/* Setup signal handlers
************************/
pcntl_signal(SIGTERM, "INT_handler"); // shutdown
pcntl_signal(SIGHUP,  "INT_handler"); // restart


/* Get command line arguments
*****************************/
$campaign_id  = $argv[1];              // campaign which should be started
$user_uid     = $argv[2];              // user id
$service_flag = $argv[3];
$message_id   = $argv[4];
$user = user_load(array('uid' => $user_uid));
if (!$user) {
  watchdog('campaign ' . $campaign_id, "Invalid user id!", array(), WATCHDOG_ERROR);
}

/*****************************************************************************
*                     LOAD CAMPAIGN                                          *
*****************************************************************************/
  // include ictcore
  include_once "/usr/ictcore/core/core.php";
  do_login($user_uid);
  // load campaign type and message
  $load_campaign = "SELECT campaign_type, message_id, created_by FROM broadcast_campaign
                    WHERE campaign_id = $campaign_id ";
  $result     = db_query($load_campaign);
  $campaign   = $result->fetchAssoc();
  $message_id = $campaign['message_id'];
  $created_by = $campaign['created_by'];
  // set service_flag for campaign type
  if($campaign['campaign_type'] == "voice"){
    $service_flag = SERVICE_VOICE;
    $vMsg = new Voicemessage(NULL, array('recording' => $message_id));
    $vMsg->save();
    $vMsg->compile();
    $program_id = $vMsg->program_id;
  } else if ($campaign['campaign_type'] == "fax"){
    $service_flag = SERVICE_FAX;
    $fMsg = new Sendfax(NULL, array('document' => $message_id));
    $fMsg->save();
    $fMsg->compile();
    $program_id = $fMsg->program_id;
  } else{
    $service_flag = false;
  }

/*****************************************************************************
*                     START OF CAMPAIGN BROADCASTING                         *
*****************************************************************************/
watchdog('campaign ' . $campaign_id, "##[ New Campaign started ]##", array(), WATCHDOG_INFO);

  $SQL = "SELECT cc.contact_id FROM broadcast_campaign_contact cc
          WHERE cc.campaign_id = $campaign_id AND status='pending'";
  $contact_id = db_query($SQL);
  if (!$contact_id) {
    watchdog('campaign ' .  $campaign_id, "no contacts found in campaign", array('%numbers' => $contact_id->fetchField()), WATCHDOG_WARNING);
   continue;
  }
  while ($contact = $contact_id->fetchAssoc()) {
    // prepare new transmission
    $oTransmission = new Transmission();
    $oTransmission->set('service_flag', $service_flag);
    $oTransmission->set('account_id',   $created_by);
    $oTransmission->set('origin', 'web');
    $oTransmission->set('direction', 'outbound');

    $oTransmission->set('contact_id', $contact['contact_id']);
//    $oTransmission->oContact->set('phone', $contact);

    $oTransmission->set('program_id', $program_id);
//    $oTransmission->oMessage->set('file_name', $file_name);
    $oTransmission->send();
    $transmission_id = $oTransmission->get('transmission_id');
    update_campaign_contact_status($contact['contact_id'], $campaign_id, $transmission_id);
    campaign_log($campaign_id, $contact['contact_id']);
  }
  update_campaign_status($campaign_id);


function update_campaign_status($campaign_id){
  $sql    = "UPDATE broadcast_campaign SET status = '16' WHERE campaign_id = :campaign_id";
  $result = db_query($sql, array(':campaign_id'=>$campaign_id));
}

function campaign_log($campaign_id, $contact_id){

  $contact = get_contact_by_id($contact_id);
  $sql     = "INSERT INTO broadcast_campaign_log (campaign_id, contact, status, start_at) VALUES ($campaign_id, $contact, 'Complete', '".time()."')";
  $result  = db_query($sql);
}

function get_contact_by_id($contact_id){
  $sql     = 'SELECT phone FROM contact WHERE contact_id = :contact_id';
  $result  = CoreDB::db_query($sql, array(':contact_id'=>$contact_id));
  $contact = $result->fetchAssoc();
  return $contact['phone'];
}

function update_campaign_contact_status($contact_id, $campaign_id, $transmission_id){
  $sql    = "UPDATE broadcast_campaign_contact SET status = 'Process', transmission_id = $transmission_id WHERE contact_id = $contact_id AND campaign_id = :campaign_id";
  $result = db_query($sql, array(':campaign_id'=>$campaign_id));
}


?>
