<?php
/******************************************************************
* Copyright © 2012 ICT Innovations, All Rights Reserved           *
* License: GNU AGPL V 3.0                                         *
* Developed By: Nasir Iqbal                                       *
*             : Tahir Almas                                       *
* Modified By:  Falak Nawaz                                       *
* Website : http://www.ictinnovations.com/                        *
* Contact : support@ictinnovations.com, info@ictinnovations.com   *
******************************************************************/

// $Id: broadcast_dummy.module,v 1.0 2009/10/16 18:08:59 ictinnovations Exp $

function broadcast_dummy_supported_services() {
  $services = array('sms' => 'Dummy SMS Service');

  return $services;
}

function broadcast_dummy_load($service) {
  watchdog('dummy gateway', t('gateway initilized for @service'), array('@service' => $service), WATCHDOG_INFO);
  return TRUE;
}

function broadcast_dummy_message_prepare($service, $message) {
  watchdog('dummy gateway', t('@service message prepared'), array('@service' => $service), WATCHDOG_INFO);
  return $message;
}

function broadcast_dummy_is_ready($service) {
  watchdog('dummy gateway', t('gateway is ready for @service'), array('@service' => $service), WATCHDOG_INFO);
  return TRUE;
}

function broadcast_dummy_deliver_sms($phone , $message, $parmeters = array()) {
  watchdog('dummy gateway', t('sms sent to: @phone, message: @message'), array('@phone' => $phone, '@message' => $message), WATCHDOG_INFO);
  return TRUE;
}
